DELETE http://localhost:8000/api/measure/2
Content-Type: application/json


###
PUT http://localhost:8000/api/measure/2
Content-Type: application/json

{
  "name": "Вес",
  "si": "кг"
}

###
POST http://localhost:8000/api/measure
Content-Type: application/json

{
  "name": "Вес",
  "si": "г"
}

###
GET http://localhost:8000/api/measure
Accept: application/json

###


